/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABodyText: typeof import('./src/components/common/ABodyText.vue')['default']
    ABtn: typeof import('./src/components/form/ABtn.vue')['default']
    ABtnIcon: typeof import('./src/components/form/ABtnIcon.vue')['default']
    ABtnIconEnter: typeof import('./src/components/form/ABtnIconEnter.vue')['default']
    ABtnOutlineSmall: typeof import('./src/components/form/ABtnOutlineSmall.vue')['default']
    ACarousel: typeof import('./src/components/common/ACarousel.vue')['default']
    ACheckbox: typeof import('./src/components/form/ACheckbox.vue')['default']
    ADialog: typeof import('./src/components/common/ADialog.vue')['default']
    ADialogContent: typeof import('./src/components/common/ADialogContent.vue')['default']
    ADialogFull: typeof import('./src/components/common/ADialogFull.vue')['default']
    AField: typeof import('./src/components/form/AField.vue')['default']
    AInput: typeof import('./src/components/form/AInput.vue')['default']
    AInputVee: typeof import('./src/components/form/AInputVee.vue')['default']
    AItem: typeof import('./src/components/common/AItem.vue')['default']
    APagination: typeof import('./src/components/common/APagination.vue')['default']
    ASelect: typeof import('./src/components/form/ASelect.vue')['default']
    ASubtitle: typeof import('./src/components/common/ASubtitle.vue')['default']
    ASvg: typeof import('./src/components/common/ASvg.vue')['default']
    ATag: typeof import('./src/components/common/ATag.vue')['default']
    ATitle: typeof import('./src/components/common/ATitle.vue')['default']
    AvatarAndNickname: typeof import('./src/components/AvatarAndNickname.vue')['default']
    BookStoreCard: typeof import('./src/components/BookStoreCard.vue')['default']
    ImageCard: typeof import('./src/components/ImageCard.vue')['default']
    ImageCardContent: typeof import('./src/components/ImageCardContent.vue')['default']
    ImageCardContentSmall: typeof import('./src/components/ImageCardContentSmall.vue')['default']
    InfoItem: typeof import('./src/components/common/InfoItem.vue')['default']
    MainCard: typeof import('./src/components/main/MainCard.vue')['default']
    MenuCard: typeof import('./src/components/main/MenuCard.vue')['default']
    MenuItem: typeof import('./src/components/main/MenuItem.vue')['default']
    MobileAuth: typeof import('./src/components/auth/MobileAuth.vue')['default']
    ReportAlert: typeof import('./src/components/auth/ReportAlert.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SDialog: typeof import('./src/components/common/SDialog.vue')['default']
    SocialLoginGroup: typeof import('./src/components/auth/SocialLoginGroup.vue')['default']
    STable: typeof import('./src/components/common/STable.vue')['default']
    TextCounter: typeof import('./src/components/form/TextCounter.vue')['default']
  }
}
